const dbItems = [
  {
    id: 1,
    name: "Poção de Cura (Tequila)",
    description:
      "Dose para restaurar 1d4 pontos de vida mental. Tequila Prata com sal e limão.",
    productType: "shot",
    fullPrice: 15.0,
    discountPrice: 12.0,
    isDiscounted: true,
    isOnShotWheel: true,
  },
  {
    id: 2,
    name: "Gota de Kriptonita",
    description:
      "Shot verde e intenso que enfraquece a resistência. Jägermeister em energético.",
    productType: "shot",
    fullPrice: 20.0,
    discountPrice: 15.0,
    isDiscounted: true,
    isOnShotWheel: true,
  },
  {
    id: 3,
    name: "Feitiço Desconjurar",
    description: "Bebida com alto teor mágico e alcoólico. Absinto Verde.",
    productType: "shot",
    fullPrice: 30.0,
    discountPrice: 25.0,
    isDiscounted: true,
    isOnShotWheel: true,
  },
  {
    id: 4,
    name: "Néctar dos Deuses (Cachaça)",
    description:
      "Shot lendário envelhecido em carvalho. Cachaça Artesanal Ouro.",
    productType: "shot",
    fullPrice: 12.0,
    discountPrice: 10.0,
    isDiscounted: true,
    isOnShotWheel: true,
  },
  {
    id: 5,
    name: "Geladeira Criogênica",
    description:
      "Tão gelada que congela a mente. Dose extra gelada de Vodka Premium.",
    productType: "shot",
    fullPrice: 18.0,
    discountPrice: 15.0,
    isDiscounted: true,
    isOnShotWheel: true,
  },
  {
    id: 6,
    name: "Fogo do Dragão",
    description:
      "Sambuca com grãos de café, levemente flambado, para queimar os inimigos.",
    productType: "shot",
    fullPrice: 22.0,
    discountPrice: 22.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 7,
    name: "Essência de Esmagar",
    description: "Shot forte de Whisky Bourbon americano, 8 anos.",
    productType: "shot",
    fullPrice: 28.0,
    discountPrice: 28.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 8,
    name: "Lágrimas de Unicórnio",
    description: "Shot puro e cristalino de Gin London Dry.",
    productType: "shot",
    fullPrice: 17.0,
    discountPrice: 17.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 9,
    name: "Hálito Congelante",
    description: "Shot doce e refrescante de Licor de Menta.",
    productType: "shot",
    fullPrice: 14.0,
    discountPrice: 14.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 10,
    name: "Anel de Fogo",
    description: "Whisky com sabor intenso de canela (Fireball).",
    productType: "shot",
    fullPrice: 19.0,
    discountPrice: 19.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 11,
    name: "Grogue do Pirata",
    description: "Shot de Run com um toque de coco.",
    productType: "shot",
    fullPrice: 16.0,
    discountPrice: 16.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 12,
    name: "Portal para Tarth",
    description: "Shot gelado de Vodka Absolut sabor limão.",
    productType: "shot",
    fullPrice: 21.0,
    discountPrice: 21.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 13,
    name: "Grimório do Pêssego",
    description: "Licor de Pêssego com uma leve camada de creme.",
    productType: "shot",
    fullPrice: 13.0,
    discountPrice: 13.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 14,
    name: "Rolagem de Perícia",
    description: "O bartender escolhe o seu shot. Resultado aleatório de 1d20!",
    productType: "shot",
    fullPrice: 20.0,
    discountPrice: 20.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 15,
    name: "Sangue de Targaryen",
    description: "Shot de cachaça com mel e limão.",
    productType: "shot",
    fullPrice: 10.0,
    discountPrice: 10.0,
    isDiscounted: false,
    isOnShotWheel: true,
  },
  {
    id: 16,
    name: "Esmeralda de Saria",
    description:
      "Drink refrescante e verde. Rum, hortelã, açúcar, limão e água com gás (Mojito).",
    productType: "drink",
    fullPrice: 25.0,
    discountPrice: 25.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 17,
    name: "Fúria da Amazona",
    description: "Caipirinha de Limão Tradicional, forte e poderosa.",
    productType: "drink",
    fullPrice: 18.0,
    discountPrice: 18.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 18,
    name: "Tônico da Sabedoria",
    description: "Gin Tônica com limão siciliano, para clarear a mente.",
    productType: "drink",
    fullPrice: 35.0,
    discountPrice: 35.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 19,
    name: "Areias de Tatooine",
    description:
      "Drink de tequila, Cointreau e suco de limão com borda de sal (Margarita).",
    productType: "drink",
    fullPrice: 28.0,
    discountPrice: 28.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 20,
    name: "A Revolução Cubana",
    description: "Rum, refrigerante de cola e limão (Cuba Libre).",
    productType: "drink",
    fullPrice: 22.0,
    discountPrice: 22.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 21,
    name: "O Testamento do Jedi",
    description:
      "Clássico robusto. Whisky Bourbon, açúcar, Angostura e casca de laranja (Old Fashioned).",
    productType: "drink",
    fullPrice: 40.0,
    discountPrice: 40.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 22,
    name: "Poder de Atena",
    description:
      "Drink frutado e doce. Vodka, licor de pêssego, suco de laranja e cranberry (Sex on the Beach).",
    productType: "drink",
    fullPrice: 26.0,
    discountPrice: 26.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 23,
    name: "A Bênção do Sol",
    description: "Aperol, Prosecco e água com gás (Aperol Spritz).",
    productType: "drink",
    fullPrice: 32.0,
    discountPrice: 32.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 24,
    name: "Tesouro da Ilha da Caveira",
    description: "Rum, leite de coco e suco de abacaxi (Pina Colada).",
    productType: "drink",
    fullPrice: 27.0,
    discountPrice: 27.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 25,
    name: "Martelo de Thor",
    description:
      "Vodka, cerveja de gengibre e limão, servido na caneca de cobre (Moscow Mule).",
    productType: "drink",
    fullPrice: 38.0,
    discountPrice: 38.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 26,
    name: "Água Mineral com Gás",
    description: "Garrafa de água mineral com gás (500ml).",
    productType: "softdrink",
    fullPrice: 5.0,
    discountPrice: 5.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 27,
    name: "Água Mineral Sem Gás",
    description: "Garrafa de água mineral sem gás (500ml).",
    productType: "softdrink",
    fullPrice: 4.0,
    discountPrice: 4.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 28,
    name: "Refrigerante Cola Lata",
    description: "Refrigerante sabor cola (350ml).",
    productType: "softdrink",
    fullPrice: 7.0,
    discountPrice: 7.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 29,
    name: "Refrigerante Limão Lata",
    description: "Refrigerante sabor limão (350ml).",
    productType: "softdrink",
    fullPrice: 7.0,
    discountPrice: 7.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 30,
    name: "Refrigerante Laranja Lata",
    description: "Refrigerante sabor laranja (350ml).",
    productType: "softdrink",
    fullPrice: 7.0,
    discountPrice: 7.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 31,
    name: "Suco de Laranja Natural",
    description: "Copo de suco de laranja natural e fresco (300ml).",
    productType: "softdrink",
    fullPrice: 12.0,
    discountPrice: 12.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 32,
    name: "Refrigerante Guaraná 600ml",
    description: "Refrigerante sabor guaraná em garrafa (600ml).",
    productType: "softdrink",
    fullPrice: 10.0,
    discountPrice: 10.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 33,
    name: "Água Tônica Lata",
    description: "Água tônica clássica (350ml).",
    productType: "softdrink",
    fullPrice: 8.0,
    discountPrice: 8.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 34,
    name: "Suco de Abacaxi com Hortelã",
    description:
      "Copo de suco de abacaxi com um toque refrescante de hortelã (300ml).",
    productType: "softdrink",
    fullPrice: 14.0,
    discountPrice: 14.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 35,
    name: "Refrigerante Limão 600ml",
    description: "Refrigerante sabor limão em garrafa (600ml).",
    productType: "softdrink",
    fullPrice: 10.0,
    discountPrice: 10.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 36,
    name: "Raízes do Hobbits",
    description: "Batatas fritas crocantes com sal e tempero da casa.",
    productType: "food",
    fullPrice: 25.0,
    discountPrice: 25.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 37,
    name: "Moedas de Ouro do Mago",
    description: "10 mini pastéis recheados com queijo mussarela.",
    productType: "food",
    fullPrice: 32.0,
    discountPrice: 32.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 38,
    name: "Olhos de Sauron",
    description:
      "Porção de anéis de cebola empanados e fritos, servidos com molho barbecue.",
    productType: "food",
    fullPrice: 28.0,
    discountPrice: 28.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 39,
    name: "Suprimentos da Guilda",
    description:
      "Tábua de Frios Simples: Queijo, salame, presunto e azeitonas.",
    productType: "food",
    fullPrice: 45.0,
    discountPrice: 45.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
  {
    id: 40,
    name: "O Bife do Caçador",
    description: "Espetinho de carne bovina temperada e grelhada.",
    productType: "food",
    fullPrice: 15.0,
    discountPrice: 15.0,
    isDiscounted: false,
    isOnShotWheel: false,
  },
];

export default dbItems;
